name: safedice
dependencies:
- python=3.6
- cudatoolkit=11.2
- cudnn=8.1
- numpy<1.19
- matplotlib
- tqdm
- patchelf
- pip
- cffi
- cython
- lockfile
- pip:
  - tensorflow-gpu==2.5.0
  - tensorflow-gan==2.0.0
  - tensorflow-probability==0.11.1
  - gym==0.17.3
  - pyglib==0.1
  - scipy
  - tf-agents==0.6.0
  - cloudpickle==1.3
  - wandb
  - tqdm
  - stable-baselines3  # for vectorized env